- name: 发送 Commit 信息
  uses: Y2Nk4/qmsg-action@master
    with:
      groups: ${{ secrets.QMSG_NOTIFY_QQ }}
      key: ${{ secrets.QMSG_KEY }}
      message: '${{ github.actor }} 针对 ${{ github.repository }} ${{ github.ref }} 的提交 ${{ github.sha }} (${{ github.event.head_commit.message }}) 的 ${{ github.workflow }} 任务部署完成'
